package wicket.addons.hibernate.dao;

/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 */
public abstract class _RootDAO extends wicket.addons.hibernate.base._BaseRootDAO {
}