package wicket.addons.hibernate.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the workitems table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="workitems"
 */
public abstract class BaseWorkitems  implements Serializable {

	public static String PROP_STATUS = "Status";
	public static String PROP_LAST_MODIFIED = "LastModified";
	public static String PROP_WORK_ITEM_GROUP_ID = "WorkItemGroupId";
	public static String PROP_DESCRIPTION = "Description";
	public static String PROP_HEADLINE = "Headline";
	public static String PROP_PRIORITY = "Priority";
	public static String PROP_CREATED = "Created";
	public static String PROP_ID = "Id";
	public static String PROP_OWNER_ID = "OwnerId";
	public static String PROP_REQUESTER_EMAIL = "RequesterEmail";
	public static String PROP_REQUESTER = "Requester";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.util.Date _created;
	private java.lang.String _requester;
	private java.lang.String _requesterEmail;
	private java.lang.String _description;
	private java.lang.Integer _ownerId;
	private java.util.Date _lastModified;
	private java.lang.Integer _workItemGroupId;
	private java.lang.Integer _status;
	private java.lang.Integer _priority;
	private java.lang.String _headline;


	// constructors
	public BaseWorkitems () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseWorkitems (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseWorkitems (
		java.lang.Integer _id,
		java.util.Date _created,
		java.lang.String _description,
		java.util.Date _lastModified,
		java.lang.Integer _status,
		java.lang.Integer _priority,
		java.lang.String _headline) {

		this.setId(_id);
		this.setCreated(_created);
		this.setDescription(_description);
		this.setLastModified(_lastModified);
		this.setStatus(_status);
		this.setPriority(_priority);
		this.setHeadline(_headline);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="identity"
     *  column="id"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: created
	 */
	public java.util.Date getCreated () {
		return _created;
	}

	/**
	 * Set the value related to the column: created
	 * @param _created the created value
	 */
	public void setCreated (java.util.Date _created) {
		this._created = _created;
	}


	/**
	 * Return the value associated with the column: requester
	 */
	public java.lang.String getRequester () {
		return _requester;
	}

	/**
	 * Set the value related to the column: requester
	 * @param _requester the requester value
	 */
	public void setRequester (java.lang.String _requester) {
		this._requester = _requester;
	}


	/**
	 * Return the value associated with the column: requesterEmail
	 */
	public java.lang.String getRequesterEmail () {
		return _requesterEmail;
	}

	/**
	 * Set the value related to the column: requesterEmail
	 * @param _requesterEmail the requesterEmail value
	 */
	public void setRequesterEmail (java.lang.String _requesterEmail) {
		this._requesterEmail = _requesterEmail;
	}


	/**
	 * Return the value associated with the column: description
	 */
	public java.lang.String getDescription () {
		return _description;
	}

	/**
	 * Set the value related to the column: description
	 * @param _description the description value
	 */
	public void setDescription (java.lang.String _description) {
		this._description = _description;
	}


	/**
	 * Return the value associated with the column: ownerId
	 */
	public java.lang.Integer getOwnerId () {
		return _ownerId;
	}

	/**
	 * Set the value related to the column: ownerId
	 * @param _ownerId the ownerId value
	 */
	public void setOwnerId (java.lang.Integer _ownerId) {
		this._ownerId = _ownerId;
	}


	/**
	 * Return the value associated with the column: lastModified
	 */
	public java.util.Date getLastModified () {
		return _lastModified;
	}

	/**
	 * Set the value related to the column: lastModified
	 * @param _lastModified the lastModified value
	 */
	public void setLastModified (java.util.Date _lastModified) {
		this._lastModified = _lastModified;
	}


	/**
	 * Return the value associated with the column: workItemGroupId
	 */
	public java.lang.Integer getWorkItemGroupId () {
		return _workItemGroupId;
	}

	/**
	 * Set the value related to the column: workItemGroupId
	 * @param _workItemGroupId the workItemGroupId value
	 */
	public void setWorkItemGroupId (java.lang.Integer _workItemGroupId) {
		this._workItemGroupId = _workItemGroupId;
	}


	/**
	 * Return the value associated with the column: status
	 */
	public java.lang.Integer getStatus () {
		return _status;
	}

	/**
	 * Set the value related to the column: status
	 * @param _status the status value
	 */
	public void setStatus (java.lang.Integer _status) {
		this._status = _status;
	}


	/**
	 * Return the value associated with the column: priority
	 */
	public java.lang.Integer getPriority () {
		return _priority;
	}

	/**
	 * Set the value related to the column: priority
	 * @param _priority the priority value
	 */
	public void setPriority (java.lang.Integer _priority) {
		this._priority = _priority;
	}


	/**
	 * Return the value associated with the column: headline
	 */
	public java.lang.String getHeadline () {
		return _headline;
	}

	/**
	 * Set the value related to the column: headline
	 * @param _headline the headline value
	 */
	public void setHeadline (java.lang.String _headline) {
		this._headline = _headline;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof wicket.addons.hibernate.base.BaseWorkitems)) return false;
		else {
			wicket.addons.hibernate.base.BaseWorkitems mObj = (wicket.addons.hibernate.base.BaseWorkitems) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}