package wicket.addons.hibernate.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the addons table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="addons"
 */
public abstract class BaseAddons  implements Serializable {

	public static String PROP_LAST_MODIFIED = "LastModified";
	public static String PROP_HOMEPAGE = "Homepage";
	public static String PROP_DESCRIPTION = "Description";
	public static String PROP_VERSION = "Version";
	public static String PROP_CREATE_TIME = "CreateTime";
	public static String PROP_LICENSE = "License";
	public static String PROP_CATEGORY_ID = "CategoryId";
	public static String PROP_WICKET_VERSION = "WicketVersion";
	public static String PROP_NAME = "Name";
	public static String PROP_ID = "Id";
	public static String PROP_OWNER_ID = "OwnerId";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.String _license;
	private java.lang.String _description;
	private java.lang.Integer _ownerId;
	private java.lang.String _homepage;
	private java.util.Date _lastModified;
	private java.util.Date _createTime;
	private java.lang.String _wicketVersion;
	private java.lang.Integer _categoryId;
	private java.lang.String _name;
	private java.lang.String _version;


	// constructors
	public BaseAddons () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseAddons (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseAddons (
		java.lang.Integer _id,
		java.lang.String _license,
		java.lang.String _description,
		java.lang.Integer _ownerId,
		java.lang.String _homepage,
		java.util.Date _lastModified,
		java.util.Date _createTime,
		java.lang.String _wicketVersion,
		java.lang.Integer _categoryId,
		java.lang.String _name,
		java.lang.String _version) {

		this.setId(_id);
		this.setLicense(_license);
		this.setDescription(_description);
		this.setOwnerId(_ownerId);
		this.setHomepage(_homepage);
		this.setLastModified(_lastModified);
		this.setCreateTime(_createTime);
		this.setWicketVersion(_wicketVersion);
		this.setCategoryId(_categoryId);
		this.setName(_name);
		this.setVersion(_version);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="identity"
     *  column="id"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: license
	 */
	public java.lang.String getLicense () {
		return _license;
	}

	/**
	 * Set the value related to the column: license
	 * @param _license the license value
	 */
	public void setLicense (java.lang.String _license) {
		this._license = _license;
	}


	/**
	 * Return the value associated with the column: description
	 */
	public java.lang.String getDescription () {
		return _description;
	}

	/**
	 * Set the value related to the column: description
	 * @param _description the description value
	 */
	public void setDescription (java.lang.String _description) {
		this._description = _description;
	}


	/**
	 * Return the value associated with the column: ownerId
	 */
	public java.lang.Integer getOwnerId () {
		return _ownerId;
	}

	/**
	 * Set the value related to the column: ownerId
	 * @param _ownerId the ownerId value
	 */
	public void setOwnerId (java.lang.Integer _ownerId) {
		this._ownerId = _ownerId;
	}


	/**
	 * Return the value associated with the column: homepage
	 */
	public java.lang.String getHomepage () {
		return _homepage;
	}

	/**
	 * Set the value related to the column: homepage
	 * @param _homepage the homepage value
	 */
	public void setHomepage (java.lang.String _homepage) {
		this._homepage = _homepage;
	}


	/**
	 * Return the value associated with the column: lastModified
	 */
	public java.util.Date getLastModified () {
		return _lastModified;
	}

	/**
	 * Set the value related to the column: lastModified
	 * @param _lastModified the lastModified value
	 */
	public void setLastModified (java.util.Date _lastModified) {
		this._lastModified = _lastModified;
	}


	/**
	 * Return the value associated with the column: createTime
	 */
	public java.util.Date getCreateTime () {
		return _createTime;
	}

	/**
	 * Set the value related to the column: createTime
	 * @param _createTime the createTime value
	 */
	public void setCreateTime (java.util.Date _createTime) {
		this._createTime = _createTime;
	}


	/**
	 * Return the value associated with the column: WicketVersion
	 */
	public java.lang.String getWicketVersion () {
		return _wicketVersion;
	}

	/**
	 * Set the value related to the column: WicketVersion
	 * @param _wicketVersion the WicketVersion value
	 */
	public void setWicketVersion (java.lang.String _wicketVersion) {
		this._wicketVersion = _wicketVersion;
	}


	/**
	 * Return the value associated with the column: categoryId
	 */
	public java.lang.Integer getCategoryId () {
		return _categoryId;
	}

	/**
	 * Set the value related to the column: categoryId
	 * @param _categoryId the categoryId value
	 */
	public void setCategoryId (java.lang.Integer _categoryId) {
		this._categoryId = _categoryId;
	}


	/**
	 * Return the value associated with the column: name
	 */
	public java.lang.String getName () {
		return _name;
	}

	/**
	 * Set the value related to the column: name
	 * @param _name the name value
	 */
	public void setName (java.lang.String _name) {
		this._name = _name;
	}


	/**
	 * Return the value associated with the column: version
	 */
	public java.lang.String getVersion () {
		return _version;
	}

	/**
	 * Set the value related to the column: version
	 * @param _version the version value
	 */
	public void setVersion (java.lang.String _version) {
		this._version = _version;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof wicket.addons.hibernate.base.BaseAddons)) return false;
		else {
			wicket.addons.hibernate.base.BaseAddons mObj = (wicket.addons.hibernate.base.BaseAddons) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}