package wicket.addons.hibernate.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the news table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="news"
 */
public abstract class BaseNews  implements Serializable {

	public static String PROP_LAST_MODIFIED = "LastModified";
	public static String PROP_HEADLINE = "Headline";
	public static String PROP_MESSAGE = "Message";
	public static String PROP_ID = "Id";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.String _message;
	private java.util.Date _lastModified;
	private java.lang.String _headline;


	// constructors
	public BaseNews () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseNews (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseNews (
		java.lang.Integer _id,
		java.lang.String _message,
		java.util.Date _lastModified,
		java.lang.String _headline) {

		this.setId(_id);
		this.setMessage(_message);
		this.setLastModified(_lastModified);
		this.setHeadline(_headline);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="identity"
     *  column="id"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: message
	 */
	public java.lang.String getMessage () {
		return _message;
	}

	/**
	 * Set the value related to the column: message
	 * @param _message the message value
	 */
	public void setMessage (java.lang.String _message) {
		this._message = _message;
	}


	/**
	 * Return the value associated with the column: lastModified
	 */
	public java.util.Date getLastModified () {
		return _lastModified;
	}

	/**
	 * Set the value related to the column: lastModified
	 * @param _lastModified the lastModified value
	 */
	public void setLastModified (java.util.Date _lastModified) {
		this._lastModified = _lastModified;
	}


	/**
	 * Return the value associated with the column: headline
	 */
	public java.lang.String getHeadline () {
		return _headline;
	}

	/**
	 * Set the value related to the column: headline
	 * @param _headline the headline value
	 */
	public void setHeadline (java.lang.String _headline) {
		this._headline = _headline;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof wicket.addons.hibernate.base.BaseNews)) return false;
		else {
			wicket.addons.hibernate.base.BaseNews mObj = (wicket.addons.hibernate.base.BaseNews) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}