package wicket.addons.hibernate.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the categories table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="categories"
 */
public abstract class BaseCategories  implements Serializable {

	public static String PROP_LAST_MODIFIED = "LastModified";
	public static String PROP_DESCRIPTION = "Description";
	public static String PROP_CREATED_BY = "CreatedBy";
	public static String PROP_DELETED = "Deleted";
	public static String PROP_NAME = "Name";
	public static String PROP_ID = "Id";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.util.Date _deleted;
	private java.lang.String _description;
	private java.util.Date _lastModified;
	private java.lang.Integer _createdBy;
	private java.lang.String _name;


	// constructors
	public BaseCategories () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseCategories (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseCategories (
		java.lang.Integer _id,
		java.lang.Integer _createdBy,
		java.lang.String _name) {

		this.setId(_id);
		this.setCreatedBy(_createdBy);
		this.setName(_name);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="identity"
     *  column="id"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: deleted
	 */
	public java.util.Date getDeleted () {
		return _deleted;
	}

	/**
	 * Set the value related to the column: deleted
	 * @param _deleted the deleted value
	 */
	public void setDeleted (java.util.Date _deleted) {
		this._deleted = _deleted;
	}


	/**
	 * Return the value associated with the column: description
	 */
	public java.lang.String getDescription () {
		return _description;
	}

	/**
	 * Set the value related to the column: description
	 * @param _description the description value
	 */
	public void setDescription (java.lang.String _description) {
		this._description = _description;
	}


	/**
	 * Return the value associated with the column: lastModified
	 */
	public java.util.Date getLastModified () {
		return _lastModified;
	}

	/**
	 * Set the value related to the column: lastModified
	 * @param _lastModified the lastModified value
	 */
	public void setLastModified (java.util.Date _lastModified) {
		this._lastModified = _lastModified;
	}


	/**
	 * Return the value associated with the column: createdBy
	 */
	public java.lang.Integer getCreatedBy () {
		return _createdBy;
	}

	/**
	 * Set the value related to the column: createdBy
	 * @param _createdBy the createdBy value
	 */
	public void setCreatedBy (java.lang.Integer _createdBy) {
		this._createdBy = _createdBy;
	}


	/**
	 * Return the value associated with the column: name
	 */
	public java.lang.String getName () {
		return _name;
	}

	/**
	 * Set the value related to the column: name
	 * @param _name the name value
	 */
	public void setName (java.lang.String _name) {
		this._name = _name;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof wicket.addons.hibernate.base.BaseCategories)) return false;
		else {
			wicket.addons.hibernate.base.BaseCategories mObj = (wicket.addons.hibernate.base.BaseCategories) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}