package wicket.addons.hibernate.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the users table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="users"
 */
public abstract class BaseUsers  implements Serializable {

	public static String PROP_LAST_MODIFIED = "LastModified";
	public static String PROP_PASSWORD = "Password";
	public static String PROP_EMAIL = "Email";
	public static String PROP_LASTNAME = "Lastname";
	public static String PROP_LOCALE = "Locale";
	public static String PROP_FIRSTNAME = "Firstname";
	public static String PROP_DEACTIVATED = "Deactivated";
	public static String PROP_NICKNAME = "Nickname";
	public static String PROP_DELETED = "Deleted";
	public static String PROP_ADMIN = "Admin";
	public static String PROP_LAST_LOGIN = "LastLogin";
	public static String PROP_ID = "Id";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.util.Date _deleted;
	private java.lang.String _password;
	private java.lang.String _locale;
	private java.lang.String _lastname;
	private java.lang.String _nickname;
	private java.util.Date _deactivated;
	private java.lang.String _firstname;
	private java.util.Date _lastModified;
	private java.lang.String _email;
	private java.util.Date _lastLogin;
	private java.lang.Integer _admin;


	// constructors
	public BaseUsers () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseUsers (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseUsers (
		java.lang.Integer _id,
		java.lang.String _password,
		java.lang.String _nickname,
		java.util.Date _lastModified,
		java.lang.String _email) {

		this.setId(_id);
		this.setPassword(_password);
		this.setNickname(_nickname);
		this.setLastModified(_lastModified);
		this.setEmail(_email);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="identity"
     *  column="id"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: deleted
	 */
	public java.util.Date getDeleted () {
		return _deleted;
	}

	/**
	 * Set the value related to the column: deleted
	 * @param _deleted the deleted value
	 */
	public void setDeleted (java.util.Date _deleted) {
		this._deleted = _deleted;
	}


	/**
	 * Return the value associated with the column: password
	 */
	public java.lang.String getPassword () {
		return _password;
	}

	/**
	 * Set the value related to the column: password
	 * @param _password the password value
	 */
	public void setPassword (java.lang.String _password) {
		this._password = _password;
	}


	/**
	 * Return the value associated with the column: locale
	 */
	public java.lang.String getLocale () {
		return _locale;
	}

	/**
	 * Set the value related to the column: locale
	 * @param _locale the locale value
	 */
	public void setLocale (java.lang.String _locale) {
		this._locale = _locale;
	}


	/**
	 * Return the value associated with the column: lastname
	 */
	public java.lang.String getLastname () {
		return _lastname;
	}

	/**
	 * Set the value related to the column: lastname
	 * @param _lastname the lastname value
	 */
	public void setLastname (java.lang.String _lastname) {
		this._lastname = _lastname;
	}


	/**
	 * Return the value associated with the column: nickname
	 */
	public java.lang.String getNickname () {
		return _nickname;
	}

	/**
	 * Set the value related to the column: nickname
	 * @param _nickname the nickname value
	 */
	public void setNickname (java.lang.String _nickname) {
		this._nickname = _nickname;
	}


	/**
	 * Return the value associated with the column: deactivated
	 */
	public java.util.Date getDeactivated () {
		return _deactivated;
	}

	/**
	 * Set the value related to the column: deactivated
	 * @param _deactivated the deactivated value
	 */
	public void setDeactivated (java.util.Date _deactivated) {
		this._deactivated = _deactivated;
	}


	/**
	 * Return the value associated with the column: firstname
	 */
	public java.lang.String getFirstname () {
		return _firstname;
	}

	/**
	 * Set the value related to the column: firstname
	 * @param _firstname the firstname value
	 */
	public void setFirstname (java.lang.String _firstname) {
		this._firstname = _firstname;
	}


	/**
	 * Return the value associated with the column: lastModified
	 */
	public java.util.Date getLastModified () {
		return _lastModified;
	}

	/**
	 * Set the value related to the column: lastModified
	 * @param _lastModified the lastModified value
	 */
	public void setLastModified (java.util.Date _lastModified) {
		this._lastModified = _lastModified;
	}


	/**
	 * Return the value associated with the column: email
	 */
	public java.lang.String getEmail () {
		return _email;
	}

	/**
	 * Set the value related to the column: email
	 * @param _email the email value
	 */
	public void setEmail (java.lang.String _email) {
		this._email = _email;
	}


	/**
	 * Return the value associated with the column: lastLogin
	 */
	public java.util.Date getLastLogin () {
		return _lastLogin;
	}

	/**
	 * Set the value related to the column: lastLogin
	 * @param _lastLogin the lastLogin value
	 */
	public void setLastLogin (java.util.Date _lastLogin) {
		this._lastLogin = _lastLogin;
	}


	/**
	 * Return the value associated with the column: admin
	 */
	public java.lang.Integer getAdmin () {
		return _admin;
	}

	/**
	 * Set the value related to the column: admin
	 * @param _admin the admin value
	 */
	public void setAdmin (java.lang.Integer _admin) {
		this._admin = _admin;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof wicket.addons.hibernate.base.BaseUsers)) return false;
		else {
			wicket.addons.hibernate.base.BaseUsers mObj = (wicket.addons.hibernate.base.BaseUsers) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}