grant principal org.apache.wicket.security.hive.authorization.TestPrincipal "basic"
{
	permission org.apache.wicket.security.hive.authorization.permissions.ComponentPermission "org.apache.wicket.security.pages.MockHomePage", "inherit, render";
	permission org.apache.wicket.security.hive.authorization.permissions.ComponentPermission "org.apache.wicket.security.pages.MockHomePage", "enable";
	permission org.apache.wicket.security.hive.authorization.permissions.ComponentPermission "org.apache.wicket.security.pages.PageA", "render";
	permission org.apache.wicket.security.hive.authorization.permissions.ComponentPermission "org.apache.wicket.security.pages.PageA", "enable";
	permission org.apache.wicket.security.hive.authorization.permissions.ComponentPermission "org.apache.wicket.security.pages.PageA:readonly", "render";
};
grant principal org.apache.wicket.security.hive.authorization.TestPrincipal "admin"
{
	permission org.apache.wicket.security.hive.authorization.permissions.ComponentPermission "org.apache.wicket.security.pages.VerySecurePage", "inherit, render";
	permission org.apache.wicket.security.hive.authorization.permissions.ComponentPermission "org.apache.wicket.security.pages.VerySecurePage", "enable";
};
