package wicket.addons.dao.dao;

import wicket.addons.dao.base.BaseCategoryDAO;

/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is the object class that relates to the CATEGORIES table.
 * Any customizations belong here.
 */
public interface CategoryDAO extends BaseCategoryDAO {
}