package wicket.addons.dao.dao;

import wicket.addons.dao.base.BaseClickDAO;

/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is the object class that relates to the CLICKS table.
 * Any customizations belong here.
 */
public interface ClickDAO extends BaseClickDAO {
}