################################################################################
# Author:        Jean-Baptiste Quenot
# Purpose:       Rake build file for pickwick
# Revision:      $Id: confstyle 130 2003-09-09 13:26:36Z jbq $
################################################################################

require "buildr"

VERSION_NUMBER = "1.0"
WICKET="org.apache.wicket:wicket:jar:1.3.0-incubating-SNAPSHOT"

repositories.remote << "http://repo2.maven.org/maven2/"

define "pickwick" do

  project.version = VERSION_NUMBER
  project.group = "org.wicketstuff"
  compile.options.target = "1.5"

  # FIXME read pom.xml instead of redefining dependencies here
  # FIXME jetty-util should be depended upon automatically
  compile.with "org.apache.wicket:wicket-guice:jar:1.3.0-incubating-SNAPSHOT", "com.google.code.guice:guice:jar:1.0", "log4j:log4j:jar:1.2.12", "org.slf4j:slf4j-log4j12:jar:1.3.1", "org.slf4j:slf4j-api:jar:1.3.1", "org.mortbay.jetty:servlet-api-2.5:jar:6.1.1", "commons-digester:commons-digester:jar:1.7", "commons-betwixt:commons-betwixt:jar:0.8", "jdom:jdom:jar:1.0", WICKET, "commons-logging:commons-logging:jar:1.1", "org.mortbay.jetty:jetty-util:jar:6.1.1", "org.mortbay.jetty:jetty:jar:6.1.1", "commons-lang:commons-lang:jar:2.3", "commons-io:commons-io:jar:1.3.1", "rome:rome:jar:0.9"
  package :jar

  package :war

  package(:zip, :classifier=>"docs", :include=>javadoc(projects).target)
end
