grant
{
	permission org.apache.wicket.security.hive.authorization.TestPermission "A", "inherit, read";
	permission org.apache.wicket.security.hive.authorization.TestPermission "A", "execute";
};
grant principal org.apache.wicket.security.hive.authorization.TestPrincipal "test1"
{
	permission org.apache.wicket.security.hive.authorization.TestPermission "1.A", "inherit, read";
	permission org.apache.wicket.security.hive.authorization.TestPermission "1.A", "execute";
};
grant principal org.apache.wicket.security.hive.authorization.TestPrincipal "test2"
{
	permission org.apache.wicket.security.hive.authorization.TestPermission "2.A", "inherit, read";
	permission org.apache.wicket.security.hive.authorization.TestPermission "2.A", "execute";
	{
	permission org.apache.wicket.security.hive.authorization.TestPermission "2.B", "inherit, read, write";
	permission org.apache.wicket.security.hive.authorization.TestPermission "2.B", "execute";
	permission org.apache.wicket.security.hive.authorization.TestPermission "2.C", "read, execute";
	permission org.apache.wicket.security.hive.authorization.TestPermission "2.C.1", "write";
	};
};
grant principal org.apache.wicket.security.hive.authorization.TestPrincipal "test3"
{
};
grant principal org.apache.wicket.security.hive.authorization.TestPrincipal "test4"
{};

grant principal org.apache.wicket.security.hive.authorization.TestPrincipal "test5"
};
grant principal org.apache.wicket.security.hive.authorization.TestPrincipal "test6"
{
	permission org.apache.wicket.security.hive.authorization.TestPermission "6.A", "inherit, read";
	permission org.apache.wicket.security.hive.authorization.TestPermission "6.A", "execute";
	permission org.apache.wicket.security.hive.authorization.TestPermission "6.B", "inherit, read, write";
	permission org.apache.wicket.security.hive.authorization.TestPermission "6.B", "execute";
	grant principal org.apache.wicket.security.hive.authorization.TestPrincipal "test7"
	{
		permission org.apache.wicket.security.hive.authorization.TestPermission "7.A", "inherit, read";
		permission org.apache.wicket.security.hive.authorization.TestPermission "7.A", "execute";
		permission org.apache.wicket.security.hive.authorization.TestPermission "7.B", "inherit, read, write";
		permission org.apache.wicket.security.hive.authorization.TestPermission "7.B", "execute";
		permission org.apache.wicket.security.hive.authorization.TestPermission "7.C", "read, execute";
		permission org.apache.wicket.security.hive.authorization.TestPermission "7.C.1", "write";
	};
	permission org.apache.wicket.security.hive.authorization.TestPermission "6.C", "read, execute";
	permission org.apache.wicket.security.hive.authorization.TestPermission "6.C.1", "write";
};
grant principal org.apache.wicket.security.hive.authorization.TestPrincipal "test8"
{
	permission org.apache.wicket.security.hive.authorization.TestPermission "8.A";
	permission org.apache.wicket.security.hive.authorization.TestPermission "8.B";
	permission org.apache.wicket.security.hive.authorization.PestTermission "8.C";
	permission org.apache.wicket.security.hive.authorization.FaultyPermission "8.D";
};
grant principal ${auth}.TestPrincipal "${test}${nine}"
{
	permission ${perm} "${nine}.A";
	permission ${perm} "${nine}.B", "test";
};
grant principal org.apache.wicket.security.hive.authorization.TestPrincipal "test10"
	permission org.apache.wicket.security.hive.authorization.TestPermission "10.A";
{
	permission org.apache.wicket.security.hive.authorization.TestPermission "10.B";