package wicket.addons.dao.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the CATEGORIES table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="CATEGORIES"
 */
public abstract class BaseCategory  implements Serializable {

	public static String PROP_LAST_MODIFIED = "lastModified";
	public static String PROP_DESCRIPTION = "description";
	public static String PROP_CREATED_BY = "createdBy";
	public static String PROP_DELETED = "deleted";
	public static String PROP_NAME = "name";
	public static String PROP_ID = "id";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private int _id;

	// fields
	private java.lang.String _name;
	private java.lang.String _description;
	private java.util.Date _lastModified;
	private java.util.Date _deleted;
	private int _createdBy;


	// constructors
	public BaseCategory () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseCategory (int _id) {
		this.setId(_id);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseCategory (
		int _id,
		java.lang.String _name,
		java.util.Date _lastModified,
		int _createdBy) {

		this.setId(_id);
		this.setName(_name);
		this.setLastModified(_lastModified);
		this.setCreatedBy(_createdBy);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="identity"
     *  column="id"
     */
	public int getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (int _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: NAME
	 */
	public java.lang.String getName () {
		return _name;
	}

	/**
	 * Set the value related to the column: NAME
	 * @param _name the NAME value
	 */
	public void setName (java.lang.String _name) {
		this._name = _name;
	}


	/**
	 * Return the value associated with the column: DESCRIPTION
	 */
	public java.lang.String getDescription () {
		return _description;
	}

	/**
	 * Set the value related to the column: DESCRIPTION
	 * @param _description the DESCRIPTION value
	 */
	public void setDescription (java.lang.String _description) {
		this._description = _description;
	}


	/**
	 * Return the value associated with the column: LASTMODIFIED
	 */
	public java.util.Date getLastModified () {
		return _lastModified;
	}

	/**
	 * Set the value related to the column: LASTMODIFIED
	 * @param _lastModified the LASTMODIFIED value
	 */
	public void setLastModified (java.util.Date _lastModified) {
		this._lastModified = _lastModified;
	}


	/**
	 * Return the value associated with the column: DELETED
	 */
	public java.util.Date getDeleted () {
		return _deleted;
	}

	/**
	 * Set the value related to the column: DELETED
	 * @param _deleted the DELETED value
	 */
	public void setDeleted (java.util.Date _deleted) {
		this._deleted = _deleted;
	}


	/**
	 * Return the value associated with the column: CREATEDBY
	 */
	public int getCreatedBy () {
		return _createdBy;
	}

	/**
	 * Set the value related to the column: CREATEDBY
	 * @param _createdBy the CREATEDBY value
	 */
	public void setCreatedBy (int _createdBy) {
		this._createdBy = _createdBy;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof wicket.addons.dao.base.BaseCategory)) return false;
		else {
			wicket.addons.dao.base.BaseCategory mObj = (wicket.addons.dao.base.BaseCategory) obj;
			return (this.getId() == mObj.getId());
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			return (int) this.getId();
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}