package wicket.addons.dao.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the CLICKS table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="CLICKS"
 */
public abstract class BaseClick  implements Serializable {

	public static String PROP_TIMESTAMP = "timestamp";
	public static String PROP_ADDON = "addon";
	public static String PROP_SESSION_ID = "sessionId";
	public static String PROP_ID = "id";
	public static String PROP_REMOTE_I_P_ADDRESS = "remoteIPAddress";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private int _id;

	// fields
	private java.util.Date _timestamp;
	private java.lang.String _sessionId;
	private java.lang.String _remoteIPAddress;

	// many to one
	private wicket.addons.dao.Addon _addon;


	// constructors
	public BaseClick () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseClick (int _id) {
		this.setId(_id);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseClick (
		int _id,
		wicket.addons.dao.Addon _addon,
		java.util.Date _timestamp) {

		this.setId(_id);
		this.setAddon(_addon);
		this.setTimestamp(_timestamp);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="identity"
     *  column="id"
     */
	public int getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (int _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: TIMESTAMP
	 */
	public java.util.Date getTimestamp () {
		return _timestamp;
	}

	/**
	 * Set the value related to the column: TIMESTAMP
	 * @param _timestamp the TIMESTAMP value
	 */
	public void setTimestamp (java.util.Date _timestamp) {
		this._timestamp = _timestamp;
	}


	/**
	 * Return the value associated with the column: SESSIONID
	 */
	public java.lang.String getSessionId () {
		return _sessionId;
	}

	/**
	 * Set the value related to the column: SESSIONID
	 * @param _sessionId the SESSIONID value
	 */
	public void setSessionId (java.lang.String _sessionId) {
		this._sessionId = _sessionId;
	}


	/**
	 * Return the value associated with the column: REMOTEIPADDRESS
	 */
	public java.lang.String getRemoteIPAddress () {
		return _remoteIPAddress;
	}

	/**
	 * Set the value related to the column: REMOTEIPADDRESS
	 * @param _remoteIPAddress the REMOTEIPADDRESS value
	 */
	public void setRemoteIPAddress (java.lang.String _remoteIPAddress) {
		this._remoteIPAddress = _remoteIPAddress;
	}


	/**
     * @hibernate.property
     *  column=addonId
	 * not-null=true
	 */
	public wicket.addons.dao.Addon getAddon () {
		return this._addon;
	}

	/**
	 * Set the value related to the column: addonId
	 * @param _addon the addonId value
	 */
	public void setAddon (wicket.addons.dao.Addon _addon) {
		this._addon = _addon;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof wicket.addons.dao.base.BaseClick)) return false;
		else {
			wicket.addons.dao.base.BaseClick mObj = (wicket.addons.dao.base.BaseClick) obj;
			return (this.getId() == mObj.getId());
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			return (int) this.getId();
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}