package wicket.addons.dao.base;

import java.io.Serializable;
import java.util.List;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the ADDONS table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="ADDONS"
 */
public abstract class BaseAddon  implements Serializable {

	public static String PROP_CLICKS_LAST24_H = "clicksLast24H";
	public static String PROP_OWNER = "owner";
	public static String PROP_HOMEPAGE = "homepage";
	public static String PROP_DOWNLOAD_URL = "downloadUrl";
	public static String PROP_CREATE_TIME = "createTime";
	public static String PROP_CLICKS_LAST_MONTH = "clicksLastMonth";
	public static String PROP_WICKET_VERSION = "wicketVersion";
	public static String PROP_LAST_MODIFIED = "lastModified";
	public static String PROP_DESCRIPTION = "description";
	public static String PROP_VERSION = "version";
	public static String PROP_CLICKS_ALL = "clicksAll";
	public static String PROP_ENABLED = "enabled";
	public static String PROP_LICENSE = "license";
	public static String PROP_CATEGORY = "category";
	public static String PROP_CLICKS_LAST_WEEK = "clicksLastWeek";
	public static String PROP_AVERAGE_RATING = "averageRating";
	public static String PROP_NAME = "name";
	public static String PROP_ID = "id";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private int _id;

	// fields
	private java.lang.String _name;
	private java.lang.String _license;
	private java.util.Date _createTime;
	private java.util.Date _lastModified;
	private java.lang.String _homepage;
	private java.lang.String _downloadUrl;
	private java.lang.String _version;
	private java.lang.String _wicketVersion;
	private java.lang.String _description;
	private int _enabled;
	private double _averageRating;
	private int _clicksLast24H;
	private int _clicksLastWeek;
	private int _clicksLastMonth;
	private int _clicksAll;

	// many to one
	private wicket.addons.dao.Category _category;
	private wicket.addons.dao.User _owner;

	// collections
	private List _comments;
	private List _ratings;
	private List _clicks;


	// constructors
	public BaseAddon () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseAddon (int _id) {
		this.setId(_id);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseAddon (
		int _id,
		wicket.addons.dao.Category _category,
		wicket.addons.dao.User _owner,
		java.lang.String _name,
		java.lang.String _license,
		java.util.Date _createTime,
		java.util.Date _lastModified,
		java.lang.String _downloadUrl,
		int _enabled,
		double _averageRating,
		int _clicksLast24H,
		int _clicksLastWeek,
		int _clicksLastMonth,
		int _clicksAll) {

		this.setId(_id);
		this.setCategory(_category);
		this.setOwner(_owner);
		this.setName(_name);
		this.setLicense(_license);
		this.setCreateTime(_createTime);
		this.setLastModified(_lastModified);
		this.setDownloadUrl(_downloadUrl);
		this.setEnabled(_enabled);
		this.setAverageRating(_averageRating);
		this.setClicksLast24H(_clicksLast24H);
		this.setClicksLastWeek(_clicksLastWeek);
		this.setClicksLastMonth(_clicksLastMonth);
		this.setClicksAll(_clicksAll);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="identity"
     *  column="id"
     */
	public int getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (int _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: NAME
	 */
	public java.lang.String getName () {
		return _name;
	}

	/**
	 * Set the value related to the column: NAME
	 * @param _name the NAME value
	 */
	public void setName (java.lang.String _name) {
		this._name = _name;
	}


	/**
	 * Return the value associated with the column: LICENSE
	 */
	public java.lang.String getLicense () {
		return _license;
	}

	/**
	 * Set the value related to the column: LICENSE
	 * @param _license the LICENSE value
	 */
	public void setLicense (java.lang.String _license) {
		this._license = _license;
	}


	/**
	 * Return the value associated with the column: CREATETIME
	 */
	public java.util.Date getCreateTime () {
		return _createTime;
	}

	/**
	 * Set the value related to the column: CREATETIME
	 * @param _createTime the CREATETIME value
	 */
	public void setCreateTime (java.util.Date _createTime) {
		this._createTime = _createTime;
	}


	/**
	 * Return the value associated with the column: LASTMODIFIED
	 */
	public java.util.Date getLastModified () {
		return _lastModified;
	}

	/**
	 * Set the value related to the column: LASTMODIFIED
	 * @param _lastModified the LASTMODIFIED value
	 */
	public void setLastModified (java.util.Date _lastModified) {
		this._lastModified = _lastModified;
	}


	/**
	 * Return the value associated with the column: HOMEPAGE
	 */
	public java.lang.String getHomepage () {
		return _homepage;
	}

	/**
	 * Set the value related to the column: HOMEPAGE
	 * @param _homepage the HOMEPAGE value
	 */
	public void setHomepage (java.lang.String _homepage) {
		this._homepage = _homepage;
	}


	/**
	 * Return the value associated with the column: DOWNLOADURL
	 */
	public java.lang.String getDownloadUrl () {
		return _downloadUrl;
	}

	/**
	 * Set the value related to the column: DOWNLOADURL
	 * @param _downloadUrl the DOWNLOADURL value
	 */
	public void setDownloadUrl (java.lang.String _downloadUrl) {
		this._downloadUrl = _downloadUrl;
	}


	/**
	 * Return the value associated with the column: VERSION
	 */
	public java.lang.String getVersion () {
		return _version;
	}

	/**
	 * Set the value related to the column: VERSION
	 * @param _version the VERSION value
	 */
	public void setVersion (java.lang.String _version) {
		this._version = _version;
	}


	/**
	 * Return the value associated with the column: WICKETVERSION
	 */
	public java.lang.String getWicketVersion () {
		return _wicketVersion;
	}

	/**
	 * Set the value related to the column: WICKETVERSION
	 * @param _wicketVersion the WICKETVERSION value
	 */
	public void setWicketVersion (java.lang.String _wicketVersion) {
		this._wicketVersion = _wicketVersion;
	}


	/**
	 * Return the value associated with the column: DESCRIPTION
	 */
	public java.lang.String getDescription () {
		return _description;
	}

	/**
	 * Set the value related to the column: DESCRIPTION
	 * @param _description the DESCRIPTION value
	 */
	public void setDescription (java.lang.String _description) {
		this._description = _description;
	}


	/**
	 * Return the value associated with the column: ENABLED
	 */
	public int getEnabled () {
		return _enabled;
	}

	/**
	 * Set the value related to the column: ENABLED
	 * @param _enabled the ENABLED value
	 */
	public void setEnabled (int _enabled) {
		this._enabled = _enabled;
	}


	/**
	 * Return the value associated with the column: AVERAGERATING
	 */
	public double getAverageRating () {
		return _averageRating;
	}

	/**
	 * Set the value related to the column: AVERAGERATING
	 * @param _averageRating the AVERAGERATING value
	 */
	public void setAverageRating (double _averageRating) {
		this._averageRating = _averageRating;
	}


	/**
	 * Return the value associated with the column: CLICKSLAST24H
	 */
	public int getClicksLast24H () {
		return _clicksLast24H;
	}

	/**
	 * Set the value related to the column: CLICKSLAST24H
	 * @param _clicksLast24H the CLICKSLAST24H value
	 */
	public void setClicksLast24H (int _clicksLast24H) {
		this._clicksLast24H = _clicksLast24H;
	}


	/**
	 * Return the value associated with the column: CLICKSLASTWEEK
	 */
	public int getClicksLastWeek () {
		return _clicksLastWeek;
	}

	/**
	 * Set the value related to the column: CLICKSLASTWEEK
	 * @param _clicksLastWeek the CLICKSLASTWEEK value
	 */
	public void setClicksLastWeek (int _clicksLastWeek) {
		this._clicksLastWeek = _clicksLastWeek;
	}


	/**
	 * Return the value associated with the column: CLICKSLASTMONTH
	 */
	public int getClicksLastMonth () {
		return _clicksLastMonth;
	}

	/**
	 * Set the value related to the column: CLICKSLASTMONTH
	 * @param _clicksLastMonth the CLICKSLASTMONTH value
	 */
	public void setClicksLastMonth (int _clicksLastMonth) {
		this._clicksLastMonth = _clicksLastMonth;
	}


	/**
	 * Return the value associated with the column: CLICKSALL
	 */
	public int getClicksAll () {
		return _clicksAll;
	}

	/**
	 * Set the value related to the column: CLICKSALL
	 * @param _clicksAll the CLICKSALL value
	 */
	public void setClicksAll (int _clicksAll) {
		this._clicksAll = _clicksAll;
	}


	/**
     * @hibernate.property
     *  column=categoryId
	 * not-null=true
	 */
	public wicket.addons.dao.Category getCategory () {
		return this._category;
	}

	/**
	 * Set the value related to the column: categoryId
	 * @param _category the categoryId value
	 */
	public void setCategory (wicket.addons.dao.Category _category) {
		this._category = _category;
	}


	/**
     * @hibernate.property
     *  column=ownerId
	 * not-null=true
	 */
	public wicket.addons.dao.User getOwner () {
		return this._owner;
	}

	/**
	 * Set the value related to the column: ownerId
	 * @param _owner the ownerId value
	 */
	public void setOwner (wicket.addons.dao.User _owner) {
		this._owner = _owner;
	}


	/**
	 * Return the value associated with the column: comments
	 */
	public List getComments () {
		return this._comments;
	}

	/**
	 * Set the value related to the column: comments
	 * @param _comments the comments value
	 */
	public void setComments (List _comments) {
		this._comments = _comments;
	}
	
	public void addToComments (Object obj) {
		if (null == this._comments) this._comments = new java.util.ArrayList();
		this._comments.add(obj);
	}



	/**
	 * Return the value associated with the column: ratings
	 */
	public List getRatings () {
		return this._ratings;
	}

	/**
	 * Set the value related to the column: ratings
	 * @param _ratings the ratings value
	 */
	public void setRatings (List _ratings) {
		this._ratings = _ratings;
	}
	
	public void addToRatings (Object obj) {
		if (null == this._ratings) this._ratings = new java.util.ArrayList();
		this._ratings.add(obj);
	}



	/**
	 * Return the value associated with the column: clicks
	 */
	public List getClicks () {
		return this._clicks;
	}

	/**
	 * Set the value related to the column: clicks
	 * @param _clicks the clicks value
	 */
	public void setClicks (List _clicks) {
		this._clicks = _clicks;
	}
	
	public void addToClicks (Object obj) {
		if (null == this._clicks) this._clicks = new java.util.ArrayList();
		this._clicks.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof wicket.addons.dao.base.BaseAddon)) return false;
		else {
			wicket.addons.dao.base.BaseAddon mObj = (wicket.addons.dao.base.BaseAddon) obj;
			return (this.getId() == mObj.getId());
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			return (int) this.getId();
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}