package net.sf.ipn.data.auto;

import java.util.List;

/**
 * Class _Category was generated by Cayenne. It is probably a good idea to avoid changing
 * this class manually, since it may be overwritten next time code is regenerated. If you
 * need to make any customizations, please use subclass.
 */
public class _Category extends org.objectstyle.cayenne.CayenneDataObject
{

	public static final String CODE_PROPERTY = "code";
	public static final String DESCRIPTION_PROPERTY = "description";
	public static final String TO_PRAYER_GROUP_CATEGORY_PROPERTY = "TO_PRAYER_GROUP_CATEGORY";
	public static final String CHILD_LIST_PROPERTY = "childList";
	public static final String PARENT_PROPERTY = "parent";

	public static final String ID_PK_COLUMN = "ID";

	public void setCode(String code)
	{
		writeProperty("code", code);
	}

	public String getCode()
	{
		return (String)readProperty("code");
	}


	public void setDescription(String description)
	{
		writeProperty("description", description);
	}

	public String getDescription()
	{
		return (String)readProperty("description");
	}


	public void addToTO_PRAYER_GROUP_CATEGORY(net.sf.ipn.data.PrayerGroupCategory obj)
	{
		addToManyTarget("TO_PRAYER_GROUP_CATEGORY", obj, true);
	}

	public void removeFromTO_PRAYER_GROUP_CATEGORY(net.sf.ipn.data.PrayerGroupCategory obj)
	{
		removeToManyTarget("TO_PRAYER_GROUP_CATEGORY", obj, true);
	}

	public List getTO_PRAYER_GROUP_CATEGORY()
	{
		return (List)readProperty("TO_PRAYER_GROUP_CATEGORY");
	}


	public void addToChildList(net.sf.ipn.data.Category obj)
	{
		addToManyTarget("childList", obj, true);
	}

	public void removeFromChildList(net.sf.ipn.data.Category obj)
	{
		removeToManyTarget("childList", obj, true);
	}

	public List getChildList()
	{
		return (List)readProperty("childList");
	}


	public void setParent(net.sf.ipn.data.Category parent)
	{
		setToOneTarget("parent", parent, true);
	}

	public net.sf.ipn.data.Category getParent()
	{
		return (net.sf.ipn.data.Category)readProperty("parent");
	}


}
