package net.sf.ipn.data.auto;

import java.util.List;

/**
 * Class _Lang was generated by Cayenne. It is probably a good idea to avoid changing this
 * class manually, since it may be overwritten next time code is regenerated. If you need
 * to make any customizations, please use subclass.
 */
public class _Lang extends org.objectstyle.cayenne.CayenneDataObject
{

	public static final String CODE_PROPERTY = "code";
	public static final String DESCRIPTION_PROPERTY = "description";
	public static final String GROUP_LIST_PROPERTY = "groupList";
	public static final String PRAYER_ITEM_LIST_PROPERTY = "prayerItemList";
	public static final String USER_LANG_LIST_PROPERTY = "userLangList";

	public static final String ID_PK_COLUMN = "ID";

	public void setCode(String code)
	{
		writeProperty("code", code);
	}

	public String getCode()
	{
		return (String)readProperty("code");
	}


	public void setDescription(String description)
	{
		writeProperty("description", description);
	}

	public String getDescription()
	{
		return (String)readProperty("description");
	}


	public void addToGroupList(net.sf.ipn.data.PrayerGroup obj)
	{
		addToManyTarget("groupList", obj, true);
	}

	public void removeFromGroupList(net.sf.ipn.data.PrayerGroup obj)
	{
		removeToManyTarget("groupList", obj, true);
	}

	public List getGroupList()
	{
		return (List)readProperty("groupList");
	}


	public void addToPrayerItemList(net.sf.ipn.data.PrayerItem obj)
	{
		addToManyTarget("prayerItemList", obj, true);
	}

	public void removeFromPrayerItemList(net.sf.ipn.data.PrayerItem obj)
	{
		removeToManyTarget("prayerItemList", obj, true);
	}

	public List getPrayerItemList()
	{
		return (List)readProperty("prayerItemList");
	}


	public void addToUserLangList(net.sf.ipn.data.UserLang obj)
	{
		addToManyTarget("userLangList", obj, true);
	}

	public void removeFromUserLangList(net.sf.ipn.data.UserLang obj)
	{
		removeToManyTarget("userLangList", obj, true);
	}

	public List getUserLangList()
	{
		return (List)readProperty("userLangList");
	}


}
