package net.sf.ipn.data.auto;

import java.util.List;

/**
 * Class _Org was generated by Cayenne. It is probably a good idea to avoid changing this
 * class manually, since it may be overwritten next time code is regenerated. If you need
 * to make any customizations, please use subclass.
 */
public class _Org extends org.objectstyle.cayenne.CayenneDataObject
{

	public static final String EMAIL_ADDRESS_PROPERTY = "emailAddress";
	public static final String NAME_PROPERTY = "name";
	public static final String WEB_ADDRESS_PROPERTY = "webAddress";
	public static final String CHILD_ORG_LIST_PROPERTY = "childOrgList";
	public static final String GROUP_LIST_PROPERTY = "groupList";
	public static final String ORG_USER_ROLE_LIST_PROPERTY = "orgUserRoleList";
	public static final String PARENT_PROPERTY = "parent";

	public static final String ID_PK_COLUMN = "ID";

	public void setEmailAddress(String emailAddress)
	{
		writeProperty("emailAddress", emailAddress);
	}

	public String getEmailAddress()
	{
		return (String)readProperty("emailAddress");
	}


	public void setName(String name)
	{
		writeProperty("name", name);
	}

	public String getName()
	{
		return (String)readProperty("name");
	}


	public void setWebAddress(String webAddress)
	{
		writeProperty("webAddress", webAddress);
	}

	public String getWebAddress()
	{
		return (String)readProperty("webAddress");
	}


	public void addToChildOrgList(net.sf.ipn.data.Org obj)
	{
		addToManyTarget("childOrgList", obj, true);
	}

	public void removeFromChildOrgList(net.sf.ipn.data.Org obj)
	{
		removeToManyTarget("childOrgList", obj, true);
	}

	public List getChildOrgList()
	{
		return (List)readProperty("childOrgList");
	}


	public void addToGroupList(net.sf.ipn.data.PrayerGroup obj)
	{
		addToManyTarget("groupList", obj, true);
	}

	public void removeFromGroupList(net.sf.ipn.data.PrayerGroup obj)
	{
		removeToManyTarget("groupList", obj, true);
	}

	public List getGroupList()
	{
		return (List)readProperty("groupList");
	}


	public void addToOrgUserRoleList(net.sf.ipn.data.OrgUserRole obj)
	{
		addToManyTarget("orgUserRoleList", obj, true);
	}

	public void removeFromOrgUserRoleList(net.sf.ipn.data.OrgUserRole obj)
	{
		removeToManyTarget("orgUserRoleList", obj, true);
	}

	public List getOrgUserRoleList()
	{
		return (List)readProperty("orgUserRoleList");
	}


	public void setParent(net.sf.ipn.data.Org parent)
	{
		setToOneTarget("parent", parent, true);
	}

	public net.sf.ipn.data.Org getParent()
	{
		return (net.sf.ipn.data.Org)readProperty("parent");
	}


}
