package net.sf.ipn.data.auto;

/**
 * Class _OrgUserRole was generated by Cayenne. It is probably a good idea to avoid
 * changing this class manually, since it may be overwritten next time code is
 * regenerated. If you need to make any customizations, please use subclass.
 */
public class _OrgUserRole extends org.objectstyle.cayenne.CayenneDataObject
{

	public static final String ORG_PROPERTY = "org";
	public static final String ROLE_PROPERTY = "role";
	public static final String USER_PROPERTY = "user";

	public static final String ID_PK_COLUMN = "ID";

	public void setOrg(net.sf.ipn.data.Org org)
	{
		setToOneTarget("org", org, true);
	}

	public net.sf.ipn.data.Org getOrg()
	{
		return (net.sf.ipn.data.Org)readProperty("org");
	}


	public void setRole(net.sf.ipn.data.Role role)
	{
		setToOneTarget("role", role, true);
	}

	public net.sf.ipn.data.Role getRole()
	{
		return (net.sf.ipn.data.Role)readProperty("role");
	}


	public void setUser(net.sf.ipn.data.User user)
	{
		setToOneTarget("user", user, true);
	}

	public net.sf.ipn.data.User getUser()
	{
		return (net.sf.ipn.data.User)readProperty("user");
	}


}
