package net.sf.ipn.data.auto;

/**
 * Class _PrayerGroupCategory was generated by Cayenne. It is probably a good idea to
 * avoid changing this class manually, since it may be overwritten next time code is
 * regenerated. If you need to make any customizations, please use subclass.
 */
public class _PrayerGroupCategory extends org.objectstyle.cayenne.CayenneDataObject
{

	public static final String TO_CATEGORY_PROPERTY = "TO_CATEGORY";
	public static final String TO_PRAYER_GROUP_PROPERTY = "TO_PRAYER_GROUP";

	public static final String ID_PK_COLUMN = "ID";

	public void setTO_CATEGORY(net.sf.ipn.data.Category TO_CATEGORY)
	{
		setToOneTarget("TO_CATEGORY", TO_CATEGORY, true);
	}

	public net.sf.ipn.data.Category getTO_CATEGORY()
	{
		return (net.sf.ipn.data.Category)readProperty("TO_CATEGORY");
	}


	public void setTO_PRAYER_GROUP(net.sf.ipn.data.PrayerGroup TO_PRAYER_GROUP)
	{
		setToOneTarget("TO_PRAYER_GROUP", TO_PRAYER_GROUP, true);
	}

	public net.sf.ipn.data.PrayerGroup getTO_PRAYER_GROUP()
	{
		return (net.sf.ipn.data.PrayerGroup)readProperty("TO_PRAYER_GROUP");
	}


}
