package net.sf.ipn.data.auto;

import java.util.List;

/**
 * Class _PrayerItemType was generated by Cayenne. It is probably a good idea to avoid
 * changing this class manually, since it may be overwritten next time code is
 * regenerated. If you need to make any customizations, please use subclass.
 */
public class _PrayerItemType extends org.objectstyle.cayenne.CayenneDataObject
{

	public static final String CODE_PROPERTY = "code";
	public static final String DESCRIPTION_PROPERTY = "description";
	public static final String TYPE_TO_PRAYER_ITEM_PROPERTY = "TYPE_TO_PRAYER_ITEM";

	public static final String ID_PK_COLUMN = "ID";

	public void setCode(String code)
	{
		writeProperty("code", code);
	}

	public String getCode()
	{
		return (String)readProperty("code");
	}


	public void setDescription(String description)
	{
		writeProperty("description", description);
	}

	public String getDescription()
	{
		return (String)readProperty("description");
	}


	public void addToTYPE_TO_PRAYER_ITEM(net.sf.ipn.data.PrayerItem obj)
	{
		addToManyTarget("TYPE_TO_PRAYER_ITEM", obj, true);
	}

	public void removeFromTYPE_TO_PRAYER_ITEM(net.sf.ipn.data.PrayerItem obj)
	{
		removeToManyTarget("TYPE_TO_PRAYER_ITEM", obj, true);
	}

	public List getTYPE_TO_PRAYER_ITEM()
	{
		return (List)readProperty("TYPE_TO_PRAYER_ITEM");
	}


}
