package net.sf.ipn.data.auto;

/**
 * Class _PrayerItem was generated by Cayenne. It is probably a good idea to avoid
 * changing this class manually, since it may be overwritten next time code is
 * regenerated. If you need to make any customizations, please use subclass.
 */
public class _PrayerItem extends org.objectstyle.cayenne.CayenneDataObject
{

	public static final String ANSWER_PROPERTY = "answer";
	public static final String ANSWER_DATE_PROPERTY = "answerDate";
	public static final String BODY_PROPERTY = "body";
	public static final String CREATION_DATE_PROPERTY = "creationDate";
	public static final String EXPIRATION_DATE_PROPERTY = "expirationDate";
	public static final String SUBJECT_PROPERTY = "subject";
	public static final String LANG_PROPERTY = "lang";
	public static final String PRAYER_GROUP_PROPERTY = "prayerGroup";
	public static final String STATUS_PROPERTY = "status";
	public static final String TYPE_PROPERTY = "type";

	public static final String ID_PK_COLUMN = "ID";

	public void setAnswer(String answer)
	{
		writeProperty("answer", answer);
	}

	public String getAnswer()
	{
		return (String)readProperty("answer");
	}


	public void setAnswerDate(java.util.Date answerDate)
	{
		writeProperty("answerDate", answerDate);
	}

	public java.util.Date getAnswerDate()
	{
		return (java.util.Date)readProperty("answerDate");
	}


	public void setBody(String body)
	{
		writeProperty("body", body);
	}

	public String getBody()
	{
		return (String)readProperty("body");
	}


	public void setCreationDate(java.util.Date creationDate)
	{
		writeProperty("creationDate", creationDate);
	}

	public java.util.Date getCreationDate()
	{
		return (java.util.Date)readProperty("creationDate");
	}


	public void setExpirationDate(java.util.Date expirationDate)
	{
		writeProperty("expirationDate", expirationDate);
	}

	public java.util.Date getExpirationDate()
	{
		return (java.util.Date)readProperty("expirationDate");
	}


	public void setSubject(String subject)
	{
		writeProperty("subject", subject);
	}

	public String getSubject()
	{
		return (String)readProperty("subject");
	}


	public void setLang(net.sf.ipn.data.Lang lang)
	{
		setToOneTarget("lang", lang, true);
	}

	public net.sf.ipn.data.Lang getLang()
	{
		return (net.sf.ipn.data.Lang)readProperty("lang");
	}


	public void setPrayerGroup(net.sf.ipn.data.PrayerGroup prayerGroup)
	{
		setToOneTarget("prayerGroup", prayerGroup, true);
	}

	public net.sf.ipn.data.PrayerGroup getPrayerGroup()
	{
		return (net.sf.ipn.data.PrayerGroup)readProperty("prayerGroup");
	}


	public void setStatus(net.sf.ipn.data.PrayerItemStatus status)
	{
		setToOneTarget("status", status, true);
	}

	public net.sf.ipn.data.PrayerItemStatus getStatus()
	{
		return (net.sf.ipn.data.PrayerItemStatus)readProperty("status");
	}


	public void setType(net.sf.ipn.data.PrayerItemType type)
	{
		setToOneTarget("type", type, true);
	}

	public net.sf.ipn.data.PrayerItemType getType()
	{
		return (net.sf.ipn.data.PrayerItemType)readProperty("type");
	}


}
