package net.sf.ipn.data.auto;

import java.util.List;

/**
 * Class _PrayerGroup was generated by Cayenne. It is probably a good idea to avoid
 * changing this class manually, since it may be overwritten next time code is
 * regenerated. If you need to make any customizations, please use subclass.
 */
public class _PrayerGroup extends org.objectstyle.cayenne.CayenneDataObject
{

	public static final String NAME_PROPERTY = "name";
	public static final String CATEGORY_LIST_PROPERTY = "categoryList";
	public static final String LANG_PROPERTY = "lang";
	public static final String OWNING_ORG_PROPERTY = "owningOrg";
	public static final String OWNING_USER_PROPERTY = "owningUser";
	public static final String PRAYER_ITEM_LIST_PROPERTY = "prayerItemList";
	public static final String SUBSCRIPTION_LIST_PROPERTY = "subscriptionList";
	public static final String SUBSCRIPTION_REQUEST_LIST_PROPERTY = "subscriptionRequestList";
	public static final String TYPE_PROPERTY = "type";

	public static final String ID_PK_COLUMN = "ID";

	public void setName(String name)
	{
		writeProperty("name", name);
	}

	public String getName()
	{
		return (String)readProperty("name");
	}


	public void addToCategoryList(net.sf.ipn.data.PrayerGroupCategory obj)
	{
		addToManyTarget("categoryList", obj, true);
	}

	public void removeFromCategoryList(net.sf.ipn.data.PrayerGroupCategory obj)
	{
		removeToManyTarget("categoryList", obj, true);
	}

	public List getCategoryList()
	{
		return (List)readProperty("categoryList");
	}


	public void setLang(net.sf.ipn.data.Lang lang)
	{
		setToOneTarget("lang", lang, true);
	}

	public net.sf.ipn.data.Lang getLang()
	{
		return (net.sf.ipn.data.Lang)readProperty("lang");
	}


	public void setOwningOrg(net.sf.ipn.data.Org owningOrg)
	{
		setToOneTarget("owningOrg", owningOrg, true);
	}

	public net.sf.ipn.data.Org getOwningOrg()
	{
		return (net.sf.ipn.data.Org)readProperty("owningOrg");
	}


	public void setOwningUser(net.sf.ipn.data.User owningUser)
	{
		setToOneTarget("owningUser", owningUser, true);
	}

	public net.sf.ipn.data.User getOwningUser()
	{
		return (net.sf.ipn.data.User)readProperty("owningUser");
	}


	public void addToPrayerItemList(net.sf.ipn.data.PrayerItem obj)
	{
		addToManyTarget("prayerItemList", obj, true);
	}

	public void removeFromPrayerItemList(net.sf.ipn.data.PrayerItem obj)
	{
		removeToManyTarget("prayerItemList", obj, true);
	}

	public List getPrayerItemList()
	{
		return (List)readProperty("prayerItemList");
	}


	public void addToSubscriptionList(net.sf.ipn.data.Subscription obj)
	{
		addToManyTarget("subscriptionList", obj, true);
	}

	public void removeFromSubscriptionList(net.sf.ipn.data.Subscription obj)
	{
		removeToManyTarget("subscriptionList", obj, true);
	}

	public List getSubscriptionList()
	{
		return (List)readProperty("subscriptionList");
	}


	public void addToSubscriptionRequestList(net.sf.ipn.data.SubscriptionRequest obj)
	{
		addToManyTarget("subscriptionRequestList", obj, true);
	}

	public void removeFromSubscriptionRequestList(net.sf.ipn.data.SubscriptionRequest obj)
	{
		removeToManyTarget("subscriptionRequestList", obj, true);
	}

	public List getSubscriptionRequestList()
	{
		return (List)readProperty("subscriptionRequestList");
	}


	public void setType(net.sf.ipn.data.PrayerGroupType type)
	{
		setToOneTarget("type", type, true);
	}

	public net.sf.ipn.data.PrayerGroupType getType()
	{
		return (net.sf.ipn.data.PrayerGroupType)readProperty("type");
	}


}
