package net.sf.ipn.data.auto;

import java.util.List;

/**
 * Class _Role was generated by Cayenne. It is probably a good idea to avoid changing this
 * class manually, since it may be overwritten next time code is regenerated. If you need
 * to make any customizations, please use subclass.
 */
public class _Role extends org.objectstyle.cayenne.CayenneDataObject
{

	public static final String CODE_PROPERTY = "code";
	public static final String DESCRIPTION_PROPERTY = "description";
	public static final String ROLE_TO_ORG_USER_ROLE_PROPERTY = "ROLE_TO_ORG_USER_ROLE";

	public static final String ID_PK_COLUMN = "ID";

	public void setCode(String code)
	{
		writeProperty("code", code);
	}

	public String getCode()
	{
		return (String)readProperty("code");
	}


	public void setDescription(String description)
	{
		writeProperty("description", description);
	}

	public String getDescription()
	{
		return (String)readProperty("description");
	}


	public void addToROLE_TO_ORG_USER_ROLE(net.sf.ipn.data.OrgUserRole obj)
	{
		addToManyTarget("ROLE_TO_ORG_USER_ROLE", obj, true);
	}

	public void removeFromROLE_TO_ORG_USER_ROLE(net.sf.ipn.data.OrgUserRole obj)
	{
		removeToManyTarget("ROLE_TO_ORG_USER_ROLE", obj, true);
	}

	public List getROLE_TO_ORG_USER_ROLE()
	{
		return (List)readProperty("ROLE_TO_ORG_USER_ROLE");
	}


}
