package net.sf.ipn.data.auto;

/**
 * Class _Subscription was generated by Cayenne. It is probably a good idea to avoid
 * changing this class manually, since it may be overwritten next time code is
 * regenerated. If you need to make any customizations, please use subclass.
 */
public class _Subscription extends org.objectstyle.cayenne.CayenneDataObject
{

	public static final String MAX_PER_SESSION_PROPERTY = "maxPerSession";
	public static final String NOTE_PROPERTY = "note";
	public static final String GROUP_PROPERTY = "group";
	public static final String USER_PROPERTY = "user";

	public static final String ID_PK_COLUMN = "ID";

	public void setMaxPerSession(Short maxPerSession)
	{
		writeProperty("maxPerSession", maxPerSession);
	}

	public Short getMaxPerSession()
	{
		return (Short)readProperty("maxPerSession");
	}


	public void setNote(String note)
	{
		writeProperty("note", note);
	}

	public String getNote()
	{
		return (String)readProperty("note");
	}


	public void setGroup(net.sf.ipn.data.PrayerGroup group)
	{
		setToOneTarget("group", group, true);
	}

	public net.sf.ipn.data.PrayerGroup getGroup()
	{
		return (net.sf.ipn.data.PrayerGroup)readProperty("group");
	}


	public void setUser(net.sf.ipn.data.User user)
	{
		setToOneTarget("user", user, true);
	}

	public net.sf.ipn.data.User getUser()
	{
		return (net.sf.ipn.data.User)readProperty("user");
	}


}
