package net.sf.ipn.data.auto;

import java.util.List;

/**
 * Class _SubscriptionRequestStatus was generated by Cayenne. It is probably a good idea
 * to avoid changing this class manually, since it may be overwritten next time code is
 * regenerated. If you need to make any customizations, please use subclass.
 */
public class _SubscriptionRequestStatus extends org.objectstyle.cayenne.CayenneDataObject
{

	public static final String CODE_PROPERTY = "code";
	public static final String DESCRIPTION_PROPERTY = "description";
	public static final String STATUS_TO_SUBSCRIPTION_REQ_PROPERTY = "STATUS_TO_SUBSCRIPTION_REQ";

	public static final String ID_PK_COLUMN = "ID";

	public void setCode(String code)
	{
		writeProperty("code", code);
	}

	public String getCode()
	{
		return (String)readProperty("code");
	}


	public void setDescription(String description)
	{
		writeProperty("description", description);
	}

	public String getDescription()
	{
		return (String)readProperty("description");
	}


	public void addToSTATUS_TO_SUBSCRIPTION_REQ(net.sf.ipn.data.SubscriptionRequest obj)
	{
		addToManyTarget("STATUS_TO_SUBSCRIPTION_REQ", obj, true);
	}

	public void removeFromSTATUS_TO_SUBSCRIPTION_REQ(net.sf.ipn.data.SubscriptionRequest obj)
	{
		removeToManyTarget("STATUS_TO_SUBSCRIPTION_REQ", obj, true);
	}

	public List getSTATUS_TO_SUBSCRIPTION_REQ()
	{
		return (List)readProperty("STATUS_TO_SUBSCRIPTION_REQ");
	}


}
