package net.sf.ipn.data.auto;

/**
 * Class _SubscriptionRequest was generated by Cayenne. It is probably a good idea to
 * avoid changing this class manually, since it may be overwritten next time code is
 * regenerated. If you need to make any customizations, please use subclass.
 */
public class _SubscriptionRequest extends org.objectstyle.cayenne.CayenneDataObject
{

	public static final String INSERT_DATE_PROPERTY = "insertDate";
	public static final String RESOLUTION_DATE_PROPERTY = "resolutionDate";
	public static final String REQUESTED_GROUP_PROPERTY = "requestedGroup";
	public static final String REQUESTED_USER_PROPERTY = "requestedUser";
	public static final String REQUESTING_USER_PROPERTY = "requestingUser";
	public static final String STATUS_PROPERTY = "status";

	public static final String ID_PK_COLUMN = "ID";

	public void setInsertDate(java.util.Date insertDate)
	{
		writeProperty("insertDate", insertDate);
	}

	public java.util.Date getInsertDate()
	{
		return (java.util.Date)readProperty("insertDate");
	}


	public void setResolutionDate(java.util.Date resolutionDate)
	{
		writeProperty("resolutionDate", resolutionDate);
	}

	public java.util.Date getResolutionDate()
	{
		return (java.util.Date)readProperty("resolutionDate");
	}


	public void setRequestedGroup(net.sf.ipn.data.PrayerGroup requestedGroup)
	{
		setToOneTarget("requestedGroup", requestedGroup, true);
	}

	public net.sf.ipn.data.PrayerGroup getRequestedGroup()
	{
		return (net.sf.ipn.data.PrayerGroup)readProperty("requestedGroup");
	}


	public void setRequestedUser(net.sf.ipn.data.User requestedUser)
	{
		setToOneTarget("requestedUser", requestedUser, true);
	}

	public net.sf.ipn.data.User getRequestedUser()
	{
		return (net.sf.ipn.data.User)readProperty("requestedUser");
	}


	public void setRequestingUser(net.sf.ipn.data.User requestingUser)
	{
		setToOneTarget("requestingUser", requestingUser, true);
	}

	public net.sf.ipn.data.User getRequestingUser()
	{
		return (net.sf.ipn.data.User)readProperty("requestingUser");
	}


	public void setStatus(net.sf.ipn.data.SubscriptionRequestStatus status)
	{
		setToOneTarget("status", status, true);
	}

	public net.sf.ipn.data.SubscriptionRequestStatus getStatus()
	{
		return (net.sf.ipn.data.SubscriptionRequestStatus)readProperty("status");
	}


}
