package net.sf.ipn.data.auto;

import java.util.List;

/**
 * Class _User was generated by Cayenne. It is probably a good idea to avoid changing this
 * class manually, since it may be overwritten next time code is regenerated. If you need
 * to make any customizations, please use subclass.
 */
public class _User extends org.objectstyle.cayenne.CayenneDataObject
{

	public static final String COUNTRY_CODE_PROPERTY = "countryCode";
	public static final String DENOMINATION_PROPERTY = "denomination";
	public static final String FAMILY_NAME_PROPERTY = "familyName";
	public static final String GIVEN_NAME_PROPERTY = "givenName";
	public static final String LAST_LOGGED_IN_DATE_PROPERTY = "lastLoggedInDate";
	public static final String LOGIN_COUNT_PROPERTY = "loginCount";
	public static final String NAME_PROPERTY = "name";
	public static final String PASSWORD_PROPERTY = "password";
	public static final String REGISTRATION_DATE_PROPERTY = "registrationDate";
	public static final String GROUP_LIST_PROPERTY = "groupList";
	public static final String MY_SUBSCRIPTIONS_REQUESTED_PROPERTY = "mySubscriptionsRequested";
	public static final String ORG_USER_ROLE_LIST_PROPERTY = "orgUserRoleList";
	public static final String STATUS_PROPERTY = "status";
	public static final String SUBSCRIPTION_LIST_PROPERTY = "subscriptionList";
	public static final String SUBSCRIPTIONS_REQUESTED_OF_ME_PROPERTY = "subscriptionsRequestedOfMe";
	public static final String USER_EMAIL_LIST_PROPERTY = "userEmailList";
	public static final String USER_LANG_LIST_PROPERTY = "userLangList";

	public static final String ID_PK_COLUMN = "ID";

	public void setCountryCode(String countryCode)
	{
		writeProperty("countryCode", countryCode);
	}

	public String getCountryCode()
	{
		return (String)readProperty("countryCode");
	}


	public void setDenomination(String denomination)
	{
		writeProperty("denomination", denomination);
	}

	public String getDenomination()
	{
		return (String)readProperty("denomination");
	}


	public void setFamilyName(String familyName)
	{
		writeProperty("familyName", familyName);
	}

	public String getFamilyName()
	{
		return (String)readProperty("familyName");
	}


	public void setGivenName(String givenName)
	{
		writeProperty("givenName", givenName);
	}

	public String getGivenName()
	{
		return (String)readProperty("givenName");
	}


	public void setLastLoggedInDate(java.util.Date lastLoggedInDate)
	{
		writeProperty("lastLoggedInDate", lastLoggedInDate);
	}

	public java.util.Date getLastLoggedInDate()
	{
		return (java.util.Date)readProperty("lastLoggedInDate");
	}


	public void setLoginCount(Integer loginCount)
	{
		writeProperty("loginCount", loginCount);
	}

	public Integer getLoginCount()
	{
		return (Integer)readProperty("loginCount");
	}


	public void setName(String name)
	{
		writeProperty("name", name);
	}

	public String getName()
	{
		return (String)readProperty("name");
	}


	public void setPassword(String password)
	{
		writeProperty("password", password);
	}

	public String getPassword()
	{
		return (String)readProperty("password");
	}


	public void setRegistrationDate(java.util.Date registrationDate)
	{
		writeProperty("registrationDate", registrationDate);
	}

	public java.util.Date getRegistrationDate()
	{
		return (java.util.Date)readProperty("registrationDate");
	}


	public void addToGroupList(net.sf.ipn.data.PrayerGroup obj)
	{
		addToManyTarget("groupList", obj, true);
	}

	public void removeFromGroupList(net.sf.ipn.data.PrayerGroup obj)
	{
		removeToManyTarget("groupList", obj, true);
	}

	public List getGroupList()
	{
		return (List)readProperty("groupList");
	}


	public void addToMySubscriptionsRequested(net.sf.ipn.data.SubscriptionRequest obj)
	{
		addToManyTarget("mySubscriptionsRequested", obj, true);
	}

	public void removeFromMySubscriptionsRequested(net.sf.ipn.data.SubscriptionRequest obj)
	{
		removeToManyTarget("mySubscriptionsRequested", obj, true);
	}

	public List getMySubscriptionsRequested()
	{
		return (List)readProperty("mySubscriptionsRequested");
	}


	public void addToOrgUserRoleList(net.sf.ipn.data.OrgUserRole obj)
	{
		addToManyTarget("orgUserRoleList", obj, true);
	}

	public void removeFromOrgUserRoleList(net.sf.ipn.data.OrgUserRole obj)
	{
		removeToManyTarget("orgUserRoleList", obj, true);
	}

	public List getOrgUserRoleList()
	{
		return (List)readProperty("orgUserRoleList");
	}


	public void setStatus(net.sf.ipn.data.UserStatus status)
	{
		setToOneTarget("status", status, true);
	}

	public net.sf.ipn.data.UserStatus getStatus()
	{
		return (net.sf.ipn.data.UserStatus)readProperty("status");
	}


	public void addToSubscriptionList(net.sf.ipn.data.Subscription obj)
	{
		addToManyTarget("subscriptionList", obj, true);
	}

	public void removeFromSubscriptionList(net.sf.ipn.data.Subscription obj)
	{
		removeToManyTarget("subscriptionList", obj, true);
	}

	public List getSubscriptionList()
	{
		return (List)readProperty("subscriptionList");
	}


	public void addToSubscriptionsRequestedOfMe(net.sf.ipn.data.SubscriptionRequest obj)
	{
		addToManyTarget("subscriptionsRequestedOfMe", obj, true);
	}

	public void removeFromSubscriptionsRequestedOfMe(net.sf.ipn.data.SubscriptionRequest obj)
	{
		removeToManyTarget("subscriptionsRequestedOfMe", obj, true);
	}

	public List getSubscriptionsRequestedOfMe()
	{
		return (List)readProperty("subscriptionsRequestedOfMe");
	}


	public void addToUserEmailList(net.sf.ipn.data.UserEmail obj)
	{
		addToManyTarget("userEmailList", obj, true);
	}

	public void removeFromUserEmailList(net.sf.ipn.data.UserEmail obj)
	{
		removeToManyTarget("userEmailList", obj, true);
	}

	public List getUserEmailList()
	{
		return (List)readProperty("userEmailList");
	}


	public void addToUserLangList(net.sf.ipn.data.UserLang obj)
	{
		addToManyTarget("userLangList", obj, true);
	}

	public void removeFromUserLangList(net.sf.ipn.data.UserLang obj)
	{
		removeToManyTarget("userLangList", obj, true);
	}

	public List getUserLangList()
	{
		return (List)readProperty("userLangList");
	}


}
